2024-03-28 21:22:34 ERROR com.jdbccrud.utility.LoggerUtil - Persistence Exception: No result found for query [FROM Person WHERE username=?1] Arguments: newDatabaseTest
2024-03-28 21:40:37 ERROR com.jdbccrud.utility.LoggerUtil - Database Access Exception: Error accessing the database
2024-03-28 21:44:18 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:47:39 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:47:39 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:49:30 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:49:30 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:51:30 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:51:30 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:52:09 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:52:09 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:53:05 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:54:06 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:55:49 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 22:00:05 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: newDatabaseTest || No result found for query [FROM Person WHERE username=?1]
2024-03-28 22:10:03 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:10:03.450910, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:10:03.450910, username='null', version=1, items=[]} || not-null property references a null or transient value : com.jdbccrud.person.Person.username
2024-03-28 22:18:27 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:18:27.856101, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:18:27.856101, username='newDatabaseTest', version=0, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(newDatabaseTest) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:31:17 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:31:17.717766, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:31:17.717766, username='NoVersionTest3', version=0, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:32:52 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:32:51.742548, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:32:51.742548, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:33:02 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:33:02.528057, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:33:02.528057, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:33:35 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:33:35.143120, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:33:35.143120, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:51:45 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 || Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 22:54:24 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 22:55:31 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 23:08:40 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: NoVersionTest2 || Error accessing the database || ARGS: NoVersionTest2 ||  this person does not exist in the DB.
